### ISSUE TITLE
Progress tracking

### ISSUE THREAD

**Issue by MattDMo** [MattDMo/NYTimesArticleAPI#1]
- [x] Fork and rename repo
- [ ] Add current PRs
- [x] Update `setup.py`
- [ ] Look into setting up tests on Travis for various Python versions
  - [ ] Which means I guess I should write some tests
- [x] Rewrite README and other docs - not properly formatted on PyPI, include "under new ownership" stuff
- [x] Convert to MIT License, which is essentially the same as the current version.
- [ ] Upload to PyPI

**Comment by Geethree** [comment]
Just catching up with all non-work related issues, good work!. 
Do you have Travis setup yet for this repository?

**Comment by prateeky2806** [comment]
Still getting errors while using api.search

C:\Program Files\Anaconda3\lib\site-packages\nytimesarticle.py in search(self, response_format, key, **kwargs)
C:\Program Files\Anaconda3\lib\site-packages\nytimesarticle.py in _options(self, **kwargs)
C:\Program Files\Anaconda3\lib\site-packages\nytimesarticle.py in _format_fq(d)
C:\Program Files\Anaconda3\lib\site-packages\nytimesarticle.py in <lambda>(x)
TypeError: Can't convert 'bytes' object to str implicitly
Is guess this repo was made to resovle this problem, I am new to this so I might be doing something wrong.
I was following this [tutorial](http://dlab.berkeley.edu/blog/scraping-new-york-times-articles-python-tutorial).
Thank You.
